# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Kotlin Gradle

on:
  push:
    branches: [ mirai ]
  pull_request:
    branches: [ mirai ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle clean
        run: ./gradlew clean
      - name: Gradle shadowjar
        run: ./gradlew shadowjar
      - uses: actions/upload-artifact@v1
        with:
          name: mirai-bot-fun-1.0-TEST-all.jar
          path: build/libs
    
